copyright: Copyright &copy; 2025 Nathan McGuire
extra:
  hide:
  - powered_by
  version:
    provider: mike
extra_css:
- assets/custom.css
markdown_extensions:
- attr_list
# Removed pymdownx.emoji extension due to configuration error
- pymdownx.highlight:
    anchor_linenums: true
    line_spans: __span
    pygments_lang_class: true
- pymdownx.inlinehilite
- pymdownx.snippets
- pymdownx.superfences:
    custom_fences:
    - class: mermaid
      format: null
      name: mermaid
- pymdownx.tabbed:
    alternate_style: true
- admonition
- pymdownx.details
nav:
- Introduction: introduction.md
- Quickstart: quickstart.md
- Installation:
  - Architecture: installation/architecture.md
  - Installation Methods: installation/installation_methods.md
  - Kubernetes: installation/kubernetes.md
  - PyPI: installation/pypi.md
  - Docker Compose: installation/docker_compose.md
  - Upgrading: installation/upgrading.md
  - Docker Builds: installation/docker_builds.md
- Using Nexus:
  - README: using_nexus/README.md
- Configuration:
  - Configuring: configuration/configuring_nexus.md
- Contributing:
  - Darwin: contributing/darwin.md
  - FastAPI: contributing/fastapi.md
  - React: contributing/react.md
  - README: contributing/README.md
- Security:
  - Security Configurations: security/security_configurations.md
  - CVEs Fixed by Release: security/cves_fixed_by_release.md
- FAQ: faq.md
- Models:
  - Users: models/users.md
  - Requests: models/requests.md
- API: api.md
plugins:
- search
- plantuml:
    cache:
      backend: disabled
    interaction:
      enabled: true
    puml_url: https://www.plantuml.com/plantuml/
    theme:
      dark: material/red-dark
      light: material/red-light
- swagger-ui-tag
site_name: Don't Touch
site_url: https://nathanmcguire.github.io/nexus
theme:
  favicon: assets/favicon.ico
  features:
  - navigation.footer
  font:
    code: Ubuntu Mono
    text: Ubuntu
  icon:
    logo: octicons/circle-slash-16
  name: material
  palette:
  - accent: deep purple
    primary: green
    scheme: slate
    toggle:
      icon: material/weather-sunny
      name: Dark mode
  - accent: deep orange
    primary: blue
    scheme: default
    toggle:
      icon: material/weather-night
      name: Light mode
