@startuml audits
!include https://raw.githubusercontent.com/nathanmcguire/nexus/main/docs/models/users.puml

class Audit {
    + audit_id: int
     --
    + action: str
    + entity_id: int
    + entity_type: str
    + timestamp: datetime
    + requested_by: int
    + request_ip: str
    + request_method: str
    + request_url: str
    + request_payload: str
    + response_status: int
}

User::id ||--o{ Audit::requested_by

@enduml