@startuml requests
!include https://raw.githubusercontent.com/nathanmcguire/nexus/main/docs/models/users.puml

class Request {
    + id: int
    + timestamp: datetime
    + requested_by_id: int
    + requested_by_ip: str
    + endpoint: str
    + entity_id: int
    + entity_type: EntityType
    + method: HttpMethod
    + headers: JSON
    + payload: JSON
    + response_status: int
    + response_headers: JSON
    + response_payload: JSON
    + log_level: LogLevel
    + metadata: JSON
}

User::id ||--o{ Request::requested_by_id

@enduml