@startuml users
class User {
    +id: int
    +guid: uuid
    +username: str
    -password: str
    +enabled: bool
    +archived: bool
    +deleted: bool
    +password: str {property} <<setter>>
    +verify_password(raw_password: str): bool
}
@enduml 