"""Disabled updated by nullable to true.

Revision ID: 1c4e8d049012
Revises: df248838e945
Create Date: 2025-04-17 14:18:55.053371

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '1c4e8d049012'
down_revision: Union[str, None] = 'df248838e945'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # Use batch mode for SQLite
    if op.get_bind().dialect.name == "sqlite":
        with op.batch_alter_table('Users') as batch_op:
            batch_op.alter_column('updated_at',
                                  existing_type=sa.DATETIME(),
                                  nullable=True)
            batch_op.alter_column('updated_by',
                                  existing_type=sa.VARCHAR(),
                                  nullable=True)
    else:
        # ### commands auto generated by Alembic - please adjust! ###
        op.alter_column('Users', 'updated_at',
                        existing_type=sa.DATETIME(),
                        nullable=True)
        op.alter_column('Users', 'updated_by',
                        existing_type=sa.VARCHAR(),
                        nullable=True)
        # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # Use batch mode for SQLite
    if op.get_bind().dialect.name == "sqlite":
        with op.batch_alter_table('Users') as batch_op:
            batch_op.alter_column('updated_by',
                                  existing_type=sa.VARCHAR(),
                                  nullable=False)
            batch_op.alter_column('updated_at',
                                  existing_type=sa.DATETIME(),
                                  nullable=False)
    else:
        # ### commands auto generated by Alembic - please adjust! ###
        op.alter_column('Users', 'updated_by',
                        existing_type=sa.VARCHAR(),
                        nullable=False)
        op.alter_column('Users', 'updated_at',
                        existing_type=sa.DATETIME(),
                        nullable=False)
        # ### end Alembic commands ###
