"""initial

Revision ID: 3bd62df6a1d5
Revises: e8fc483ea8fc
Create Date: 2025-05-01 15:11:18.740820

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '3bd62df6a1d5'
down_revision: Union[str, None] = 'e8fc483ea8fc'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('Users', sa.Column('_password', sa.String(length=128), nullable=False))
    op.add_column('Users', sa.Column('enabled', sa.Boolean(), nullable=False))
    op.add_column('Users', sa.Column('archived', sa.Boolean(), nullable=False))
    op.add_column('Users', sa.Column('deleted', sa.Boolean(), nullable=False))
    op.drop_column('Users', 'updated_by')
    op.drop_column('Users', 'created_at')
    op.drop_column('Users', 'imported_at')
    op.drop_column('Users', 'archived_by')
    op.drop_column('Users', 'unarchived_by')
    op.drop_column('Users', 'deleted_by')
    op.drop_column('Users', 'enabled_at')
    op.drop_column('Users', 'imported_by')
    op.drop_column('Users', 'undeleted_by')
    op.drop_column('Users', 'undeleted_at')
    op.drop_column('Users', 'unarchived_at')
    op.drop_column('Users', 'disabled_by')
    op.drop_column('Users', 'archived_at')
    op.drop_column('Users', 'enabled_by')
    op.drop_column('Users', 'deleted_at')
    op.drop_column('Users', 'updated_at')
    op.drop_column('Users', 'disabled_at')
    op.drop_column('Users', 'created_by')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('Users', sa.Column('created_by', sa.INTEGER(), nullable=True))
    op.add_column('Users', sa.Column('disabled_at', sa.VARCHAR(length=32), nullable=True))
    op.add_column('Users', sa.Column('updated_at', sa.DATETIME(), nullable=True))
    op.add_column('Users', sa.Column('deleted_at', sa.DATETIME(), nullable=True))
    op.add_column('Users', sa.Column('enabled_by', sa.VARCHAR(length=32), nullable=True))
    op.add_column('Users', sa.Column('archived_at', sa.DATETIME(), nullable=True))
    op.add_column('Users', sa.Column('disabled_by', sa.VARCHAR(length=32), nullable=True))
    op.add_column('Users', sa.Column('unarchived_at', sa.DATETIME(), nullable=True))
    op.add_column('Users', sa.Column('undeleted_at', sa.DATETIME(), nullable=True))
    op.add_column('Users', sa.Column('undeleted_by', sa.INTEGER(), nullable=True))
    op.add_column('Users', sa.Column('imported_by', sa.INTEGER(), nullable=True))
    op.add_column('Users', sa.Column('enabled_at', sa.VARCHAR(length=32), nullable=True))
    op.add_column('Users', sa.Column('deleted_by', sa.INTEGER(), nullable=True))
    op.add_column('Users', sa.Column('unarchived_by', sa.INTEGER(), nullable=True))
    op.add_column('Users', sa.Column('archived_by', sa.INTEGER(), nullable=True))
    op.add_column('Users', sa.Column('imported_at', sa.DATETIME(), nullable=True))
    op.add_column('Users', sa.Column('created_at', sa.DATETIME(), nullable=True))
    op.add_column('Users', sa.Column('updated_by', sa.INTEGER(), nullable=True))
    op.drop_column('Users', 'deleted')
    op.drop_column('Users', 'archived')
    op.drop_column('Users', 'enabled')
    op.drop_column('Users', '_password')
    # ### end Alembic commands ###
