"""moved auditmixin and added import audit fields

Revision ID: 6534035317c1
Revises: 1c4e8d049012
Create Date: 2025-04-20 23:09:51.600078

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '6534035317c1'
down_revision: Union[str, None] = '1c4e8d049012'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('Users', sa.Column('imported_at', sa.DateTime(), nullable=True))
    op.add_column('Users', sa.Column('imported_by', sa.Integer(), nullable=True))
    op.alter_column('Users', 'created_at',
               existing_type=sa.DATETIME(),
               nullable=True)
    op.alter_column('Users', 'created_by',
               existing_type=sa.VARCHAR(),
               type_=sa.Integer(),
               nullable=True)
    op.alter_column('Users', 'updated_by',
               existing_type=sa.VARCHAR(),
               type_=sa.Integer(),
               existing_nullable=True)
    op.alter_column('Users', 'archived_by',
               existing_type=sa.VARCHAR(),
               type_=sa.Integer(),
               existing_nullable=True)
    op.alter_column('Users', 'unarchived_by',
               existing_type=sa.VARCHAR(),
               type_=sa.Integer(),
               existing_nullable=True)
    op.alter_column('Users', 'deleted_by',
               existing_type=sa.VARCHAR(),
               type_=sa.Integer(),
               existing_nullable=True)
    op.alter_column('Users', 'undeleted_by',
               existing_type=sa.VARCHAR(),
               type_=sa.Integer(),
               existing_nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('Users', 'undeleted_by',
               existing_type=sa.Integer(),
               type_=sa.VARCHAR(),
               existing_nullable=True)
    op.alter_column('Users', 'deleted_by',
               existing_type=sa.Integer(),
               type_=sa.VARCHAR(),
               existing_nullable=True)
    op.alter_column('Users', 'unarchived_by',
               existing_type=sa.Integer(),
               type_=sa.VARCHAR(),
               existing_nullable=True)
    op.alter_column('Users', 'archived_by',
               existing_type=sa.Integer(),
               type_=sa.VARCHAR(),
               existing_nullable=True)
    op.alter_column('Users', 'updated_by',
               existing_type=sa.Integer(),
               type_=sa.VARCHAR(),
               existing_nullable=True)
    op.alter_column('Users', 'created_by',
               existing_type=sa.Integer(),
               type_=sa.VARCHAR(),
               nullable=False)
    op.alter_column('Users', 'created_at',
               existing_type=sa.DATETIME(),
               nullable=False)
    op.drop_column('Users', 'imported_by')
    op.drop_column('Users', 'imported_at')
    # ### end Alembic commands ###
