"""Timestamp Mixin Add Archived

Revision ID: df248838e945
Revises: 4f1f75dd2be4
Create Date: 2025-04-17 08:34:49.141596

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'df248838e945'
down_revision: Union[str, None] = '4f1f75dd2be4'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('Users', sa.Column('archived_at', sa.DateTime(), nullable=True))
    op.add_column('Users', sa.Column('archived_by', sa.String(), nullable=True))
    op.add_column('Users', sa.Column('unarchived_at', sa.DateTime(), nullable=True))
    op.add_column('Users', sa.Column('unarchived_by', sa.String(), nullable=True))
    op.add_column('Users', sa.Column('undeleted_at', sa.DateTime(), nullable=True))
    op.add_column('Users', sa.Column('undeleted_by', sa.String(), nullable=True))
    op.drop_column('Users', 'recovered_by')
    op.drop_column('Users', 'recovered_at')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('Users', sa.Column('recovered_at', sa.DATETIME(), nullable=True))
    op.add_column('Users', sa.Column('recovered_by', sa.VARCHAR(), nullable=True))
    op.drop_column('Users', 'undeleted_by')
    op.drop_column('Users', 'undeleted_at')
    op.drop_column('Users', 'unarchived_by')
    op.drop_column('Users', 'unarchived_at')
    op.drop_column('Users', 'archived_by')
    op.drop_column('Users', 'archived_at')
    # ### end Alembic commands ###
