import type {SidebarsConfig} from '@docusaurus/plugin-content-docs';

// This runs in Node.js - Don't use client-side code here (browser APIs, JSX...)

/**
 * Creating a sidebar enables you to:
 - create an ordered group of docs
 - render a sidebar for each doc of that group
 - provide next/previous navigation

 The sidebars can be generated from the filesystem, or explicitly defined here.

 Create as many sidebars as you want.
 */
const sidebars: SidebarsConfig = {
  // By default, Docusaurus generates a sidebar from the docs folder structure
  //tutorialSidebar: [{type: 'autogenerated', dirName: '.'}],

  // But we're not doing that.
  
  customSidebar: [
    {
      type: 'doc',
      label: 'Introduction',
      id: 'introduction',
    },
    {
      type: 'category',
      label: 'Installation',
      items: [
        'installation/architecture',
        'installation/installation_methods',
        'installation/pypi',
        'installation/kubernetes',
        'installation/docker_compose',
        'installation/upgrading',
        'installation/docker_builds',
      ],
    },
    {
      type: 'category',
      label: 'Configuration',
      items: [
        'configuration/configuring_nexus',
      ],
    },
    {
      type: 'category',
      label: 'Using Nexus',
      items: [
        'using_nexus/README',
      ],
    },
    {
      type: 'category',
      label: 'Contributing',
      items: [
        'contributing/README',
        'contributing/darwin',
        'contributing/fastapi',
        'contributing/models/common',
        'contributing/models/users',
        'contributing/react',
      ],
    },
    {
      type: 'category',
      label: 'Security',
      items: [
        'security/cves_fixed_by_release',
        'security/security_configurations',
      ],
    },
    {
      type: 'doc',
      label: 'FAQ',
      id: 'faq',
    },
    {
      type: 'doc',
      label: 'API',
      id: 'api',
    },
  ],
}


export default sidebars;
